-- ====================================================================
-- SCRIPT SQL PARA SUPABASE - CLUB TUCUMÁN BB
-- Base de Datos para Gestión de Cuotas, Actividades y Control de Deudas
-- Correo oficial: tucumanbbcuotas@gmail.com
-- ====================================================================

-- 1. TABLA DE CONFIGURACIÓN DEL CLUB
CREATE TABLE IF NOT EXISTS club_settings (
    id INT PRIMARY KEY DEFAULT 1,
    club_name TEXT NOT NULL DEFAULT 'Club Tucumán BB',
    official_gmail TEXT NOT NULL DEFAULT 'tucumanbbcuotas@gmail.com',
    phone TEXT NOT NULL DEFAULT '+54 381 423-1234',
    address TEXT NOT NULL DEFAULT 'Suipacha 1160, San Miguel de Tucumán',
    cbu_alias TEXT NOT NULL DEFAULT 'TUCUMAN.BB.OFICIAL',
    receipt_prefix TEXT NOT NULL DEFAULT 'REC',
    logo_url TEXT NOT NULL DEFAULT '/club_logo.jpg',
    pos_number INT NOT NULL DEFAULT 1,
    next_receipt_number INT NOT NULL DEFAULT 1,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. TABLA DE ACTIVIDADES (Con cuotas mensuales individuales)
CREATE TABLE IF NOT EXISTS activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT DEFAULT '',
    monthly_fee NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    category TEXT NOT NULL DEFAULT 'General', -- Básquet, Gimnasio, Salón, etc.
    schedule TEXT DEFAULT '',
    color_hex TEXT DEFAULT '#0EA5E9',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. TABLA DE SOCIOS
CREATE TABLE IF NOT EXISTS members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    dni TEXT NOT NULL UNIQUE,
    phone TEXT DEFAULT '',
    email TEXT DEFAULT '',
    category TEXT DEFAULT 'Activo', -- Formativo, Primera División, Gimnasio, Vitalicio
    join_date TEXT DEFAULT '',
    notes TEXT DEFAULT '',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. TABLA INTERMEDIA: INSCRIPCIÓN DE SOCIOS A ACTIVIDADES
CREATE TABLE IF NOT EXISTS member_activities (
    member_id BIGINT REFERENCES members(id) ON DELETE CASCADE,
    activity_id BIGINT REFERENCES activities(id) ON DELETE CASCADE,
    enrolled_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    PRIMARY KEY (member_id, activity_id)
);

-- 5. TABLA DE TALONARIOS DE RECIBOS NUMERADOS (Control correlativo y auditoría de cobranza)
CREATE TABLE IF NOT EXISTS talonarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL DEFAULT 'Talonario Oficial Tesorería', -- Nombre del talonario (ej: Tesorería General, Cobros Básquet, Salón)
    prefix TEXT NOT NULL DEFAULT 'REC',                      -- Prefijo oficial (REC, TBB, etc.)
    pos_number INT NOT NULL DEFAULT 1,                       -- Punto de Venta / Caja (0001)
    current_number INT NOT NULL DEFAULT 1,                   -- Próximo número correlativo oficial
    start_number INT NOT NULL DEFAULT 1,                     -- Número de inicio (ej: 1)
    end_number INT DEFAULT NULL,                             -- Número de finalización si es talonario físico (ej: 50, 100, 1000)
    is_active BOOLEAN NOT NULL DEFAULT TRUE,                 -- Indica si es el talonario activo para emitir
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 6. TABLA DE PAGOS Y RECIBOS EMITIDOS
CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES members(id) ON DELETE CASCADE,
    activity_id BIGINT NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
    talonario_id BIGINT REFERENCES talonarios(id) ON DELETE SET NULL,
    period_month INT NOT NULL CHECK (period_month BETWEEN 1 AND 12),
    period_year INT NOT NULL CHECK (period_year >= 2020),
    amount_paid NUMERIC(10, 2) NOT NULL,
    payment_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    payment_method TEXT NOT NULL DEFAULT 'Efectivo', -- Efectivo, Transferencia, Débito, Mercado Pago
    receipt_number TEXT NOT NULL,
    notes TEXT DEFAULT '',
    UNIQUE (member_id, activity_id, period_month, period_year)
);

-- 7. TABLA DE ROLES DEL SISTEMA
CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE, -- 'admin', 'secretario', 'entrenador'
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    can_manage_all BOOLEAN DEFAULT FALSE,
    can_register_payments BOOLEAN DEFAULT TRUE,
    can_delete BOOLEAN DEFAULT FALSE,
    can_manage_settings BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 8. TABLA DE USUARIOS DEL CLUB
CREATE TABLE IF NOT EXISTS club_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    full_name TEXT NOT NULL,
    email TEXT DEFAULT '',
    role_code TEXT NOT NULL REFERENCES roles(code) ON DELETE RESTRICT,
    pin_code TEXT DEFAULT '1234',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- ====================================================================
-- DATOS INICIALES (SEMILLA) PARA CLUB TUCUMÁN BB
-- ====================================================================

-- Configuración Institucional
INSERT INTO club_settings (id, club_name, official_gmail, phone, address, cbu_alias, receipt_prefix, logo_url, pos_number, next_receipt_number)
VALUES (1, 'Club Tucumán BB', 'tucumanbbcuotas@gmail.com', '+54 381 423-1234', 'Suipacha 1160, San Miguel de Tucumán', 'TUCUMAN.BB.OFICIAL', 'REC', '/club_logo.jpg', 1, 1)
ON CONFLICT (id) DO UPDATE 
SET official_gmail = 'tucumanbbcuotas@gmail.com', logo_url = '/club_logo.jpg';

-- Roles Oficiales
INSERT INTO roles (code, name, description, can_manage_all, can_register_payments, can_delete, can_manage_settings) VALUES
('admin', 'Administrador', 'Acceso total al sistema, cobranzas, reportes, usuarios y configuración general', true, true, true, true),
('secretario', 'Secretario', 'Gestión de socios, cobro de cuotas, emisión de recibos y exportación. Sin permisos para crear actividades, modificar cuotas, eliminar ni alterar configuración', false, true, false, false),
('entrenador', 'Entrenador / Profesor', 'Consulta de listado de socios y estado de cuotas (Al día / Deuda) para seguimiento deportivo y aviso', false, false, false, false)
ON CONFLICT (code) DO UPDATE 
SET name = EXCLUDED.name, description = EXCLUDED.description;

-- Usuarios Oficiales Iniciales
INSERT INTO club_users (username, full_name, email, role_code, pin_code, is_active) VALUES
('admin', 'Administrador Principal', 'tucumanbbcuotas@gmail.com', 'admin', '1234', true),
('secretaria', 'Secretaría Club Tucumán BB', 'secretaria@tucumanbb.com', 'secretario', '1234', true),
('entrenador', 'Prof. Juan Pérez (Básquet/Gym)', 'entrenador@tucumanbb.com', 'entrenador', '1234', true)
ON CONFLICT (username) DO NOTHING;

-- Actividades Oficiales
INSERT INTO activities (name, description, monthly_fee, category, schedule, color_hex) VALUES
('Básquetbol Formativo / Primera', 'Entrenamiento en cancha oficial de parqué y competencia asociativa', 18000.00, 'Básquet', 'Lun, Mié y Vie 19:30 a 21:30 hs', '#EA580C'),
('Gimnasio de Musculación & Cardio', 'Acceso libre a máquinas de fuerza, mancuernas y cintas', 15000.00, 'Gimnasio', 'Lun a Sáb 07:00 a 22:00 hs', '#0284C7'),
('Salón - Yoga & Flexibilidad', 'Clases guiadas en el salón multiuso del 1er piso', 12000.00, 'Salón', 'Mar y Jue 18:00 a 19:15 hs', '#8B5CF6'),
('Salón - Aeróbic & Funcional', 'Entrenamiento aeróbico con música y coreografías', 12000.00, 'Salón', 'Lun, Mié y Vie 18:00 a 19:00 hs', '#EC4899')
ON CONFLICT DO NOTHING;

-- Socios de Ejemplo
INSERT INTO members (full_name, dni, phone, email, category, join_date, notes) VALUES
('Lucas Martínez', '38456123', '+54 381 511-2233', 'lucas.martinez@gmail.com', 'Primera División', '15/02/2024', 'Capitán del equipo de básquet'),
('Mariana Gómez', '35987456', '+54 381 644-8899', 'mariana.gomez@gmail.com', 'Salón / Yoga', '10/03/2024', 'Socia de actividades de salón'),
('Carlos Benítez', '42111222', '+54 381 488-3322', 'carlos.benitez@gmail.com', 'Musculación', '05/01/2024', 'Entrena en el gimnasio'),
('Sofía Navarro', '40555666', '+54 381 722-1144', 'sofia.navarro@gmail.com', 'Actividades Combinadas', '18/04/2024', 'Realiza aeróbic y gimnasio')
ON CONFLICT (dni) DO NOTHING;

-- Asignación de Actividades a los Socios
-- Lucas: Básquet (id 1) + Gimnasio (id 2)
INSERT INTO member_activities (member_id, activity_id) VALUES (1, 1), (1, 2) ON CONFLICT DO NOTHING;
-- Mariana: Yoga (id 3)
INSERT INTO member_activities (member_id, activity_id) VALUES (2, 3) ON CONFLICT DO NOTHING;
-- Carlos: Gimnasio (id 2)
INSERT INTO member_activities (member_id, activity_id) VALUES (3, 2) ON CONFLICT DO NOTHING;
-- Sofía: Aeróbic (id 4) + Gimnasio (id 2)
INSERT INTO member_activities (member_id, activity_id) VALUES (4, 4), (4, 2) ON CONFLICT DO NOTHING;

-- Talonario Oficial de Recibos Inicial
INSERT INTO talonarios (id, name, prefix, pos_number, current_number, start_number, is_active) VALUES
(1, 'Talonario Oficial Tesorería', 'REC', 1, 1, 1, true)
ON CONFLICT (id) DO NOTHING;

-- Pagos Registrados de Ejemplo
INSERT INTO payments (member_id, activity_id, talonario_id, period_month, period_year, amount_paid, payment_method, receipt_number, notes) VALUES
(1, 1, 1, 9, 2026, 18000.00, 'Transferencia', 'REC-0001-00000001', 'Pago de cuota Básquetbol Septiembre'),
(2, 3, 1, 9, 2026, 12000.00, 'Efectivo', 'REC-0001-00000002', 'Pago mensual de Yoga')
ON CONFLICT DO NOTHING;

-- ====================================================================
-- POLÍTICAS DE SEGURIDAD (Row Level Security - RLS)
-- Permite lectura y escritura con la clave anónima (anon public key)
-- ====================================================================
ALTER TABLE club_settings ENABLE ROW LEVEL SECURITY;
-- 9. TABLA DE CATEGORÍAS DE BÁSQUETBOL (Asociación con Profesores y Planteles)
CREATE TABLE IF NOT EXISTS basketball_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    age_range TEXT DEFAULT '',
    coach_user_id BIGINT REFERENCES club_users(id) ON DELETE SET NULL,
    coach_name TEXT DEFAULT '',
    schedule TEXT DEFAULT '',
    color_hex TEXT DEFAULT '#EA580C',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Columnas adicionales para relacionar socios y profesores
ALTER TABLE members ADD COLUMN IF NOT EXISTS basketball_category_id BIGINT;
ALTER TABLE club_users ADD COLUMN IF NOT EXISTS assigned_categories TEXT;

-- Categorías de Básquetbol Iniciales del Club Tucumán BB
INSERT INTO basketball_categories (name, age_range, coach_user_id, coach_name, schedule, color_hex) VALUES
('Mosquitos / Pulguitas', '4 a 6 años', 3, 'Prof. Juan Pérez', 'Mar y Jue 17:00 a 18:00 hs', '#F97316'),
('Pre-Mini', '7 y 8 años', 3, 'Prof. Juan Pérez', 'Mar y Jue 18:00 a 19:15 hs', '#EA580C'),
('Mini Básquet', '9 y 10 años', 3, 'Prof. Juan Pérez', 'Lun, Mié y Vie 17:30 a 18:45 hs', '#D97706'),
('U13 (Pre-Infantiles)', '11 y 12 años', 3, 'Prof. Juan Pérez', 'Lun, Mié y Vie 18:45 a 20:00 hs', '#0284C7'),
('U15 (Infantiles)', '13 y 14 años', 3, 'Prof. Juan Pérez', 'Lun, Mié y Vie 20:00 a 21:15 hs', '#2563EB'),
('U17 (Cadetes)', '15 y 16 años', 3, 'Prof. Juan Pérez', 'Lun a Jue 20:30 a 22:00 hs', '#7C3AED'),
('U19 (Juveniles)', '17 y 18 años', NULL, 'A Designar', 'Mar y Jue 21:00 a 22:30 hs', '#4F46E5'),
('Primera División', 'Mayor', NULL, 'Entrenador Principal', 'Lun a Vie 21:30 a 23:30 hs', '#B91C1C'),
('Maxibásquet (+35)', 'Veteranos', 3, 'Prof. Juan Pérez', 'Sábados 15:00 a 18:00 hs', '#0D9488'),
('Básquet Femenino (Formativo)', '8 a 15 años', NULL, 'Profa. Laura Díaz', 'Mar y Jue 16:00 a 17:30 hs', '#DB2777'),
('Básquet Femenino (Primera)', 'Competencia', NULL, 'Profa. Laura Díaz', 'Lun, Mié y Vie 16:30 a 18:00 hs', '#9333EA')
ON CONFLICT DO NOTHING;

ALTER TABLE activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE members ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE talonarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE club_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE basketball_categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir lectura publica" ON club_settings FOR SELECT USING (true);
CREATE POLICY "Permitir modificacion" ON club_settings FOR ALL USING (true);

CREATE POLICY "Permitir lectura publica" ON activities FOR SELECT USING (true);
CREATE POLICY "Permitir modificacion" ON activities FOR ALL USING (true);

CREATE POLICY "Permitir lectura publica" ON members FOR SELECT USING (true);
CREATE POLICY "Permitir modificacion" ON members FOR ALL USING (true);

CREATE POLICY "Permitir lectura publica" ON member_activities FOR SELECT USING (true);
CREATE POLICY "Permitir modificacion" ON member_activities FOR ALL USING (true);

CREATE POLICY "Permitir lectura publica" ON talonarios FOR SELECT USING (true);
CREATE POLICY "Permitir modificacion" ON talonarios FOR ALL USING (true);

CREATE POLICY "Permitir lectura publica" ON payments FOR SELECT USING (true);
CREATE POLICY "Permitir modificacion" ON payments FOR ALL USING (true);

CREATE POLICY "Permitir lectura publica" ON roles FOR SELECT USING (true);
CREATE POLICY "Permitir modificacion" ON roles FOR ALL USING (true);

CREATE POLICY "Permitir lectura publica" ON club_users FOR SELECT USING (true);
CREATE POLICY "Permitir modificacion" ON club_users FOR ALL USING (true);

CREATE POLICY "Permitir lectura publica" ON basketball_categories FOR SELECT USING (true);
CREATE POLICY "Permitir modificacion" ON basketball_categories FOR ALL USING (true);

