-- ====================================================================
-- SCRIPT SQL PARA SUPABASE - CLUB TUCUMÁN BB
-- Base de Datos para Gestión de Cuotas, Actividades y Control de Deudas
-- Correo oficial: tucumanbbcuotas@gmail.com
-- ====================================================================

-- 1. TABLA DE CONFIGURACIÓN DEL CLUB
CREATE TABLE IF NOT EXISTS club_settings (
    id INT PRIMARY KEY DEFAULT 1,
    club_name TEXT NOT NULL DEFAULT 'Club Tucumán BB',
    official_gmail TEXT NOT NULL DEFAULT 'tucumanbbcuotas@gmail.com',
    phone TEXT NOT NULL DEFAULT '+54 381 423-1234',
    address TEXT NOT NULL DEFAULT 'Suipacha 1160, San Miguel de Tucumán',
    cbu_alias TEXT NOT NULL DEFAULT 'TUCUMAN.BB.OFICIAL',
    receipt_prefix TEXT NOT NULL DEFAULT 'TBB',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. TABLA DE ACTIVIDADES (Con cuotas mensuales individuales)
CREATE TABLE IF NOT EXISTS activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT DEFAULT '',
    monthly_fee NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    category TEXT NOT NULL DEFAULT 'General', -- Básquet, Gimnasio, Salón, etc.
    schedule TEXT DEFAULT '',
    color_hex TEXT DEFAULT '#0EA5E9',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. TABLA DE SOCIOS
CREATE TABLE IF NOT EXISTS members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    dni TEXT NOT NULL UNIQUE,
    phone TEXT DEFAULT '',
    email TEXT DEFAULT '',
    category TEXT DEFAULT 'Activo', -- Formativo, Primera División, Gimnasio, Vitalicio
    join_date TEXT DEFAULT '',
    notes TEXT DEFAULT '',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. TABLA INTERMEDIA: INSCRIPCIÓN DE SOCIOS A ACTIVIDADES
CREATE TABLE IF NOT EXISTS member_activities (
    member_id BIGINT REFERENCES members(id) ON DELETE CASCADE,
    activity_id BIGINT REFERENCES activities(id) ON DELETE CASCADE,
    enrolled_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    PRIMARY KEY (member_id, activity_id)
);

-- 5. TABLA DE PAGOS Y RECIBOS
CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES members(id) ON DELETE CASCADE,
    activity_id BIGINT NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
    period_month INT NOT NULL CHECK (period_month BETWEEN 1 AND 12),
    period_year INT NOT NULL CHECK (period_year >= 2020),
    amount_paid NUMERIC(10, 2) NOT NULL,
    payment_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    payment_method TEXT NOT NULL DEFAULT 'Efectivo', -- Efectivo, Transferencia, Débito, Mercado Pago
    receipt_number TEXT NOT NULL,
    notes TEXT DEFAULT '',
    UNIQUE (member_id, activity_id, period_month, period_year)
);

-- ====================================================================
-- DATOS INICIALES (SEMILLA) PARA CLUB TUCUMÁN BB
-- ====================================================================

-- Configuración Institucional
INSERT INTO club_settings (id, club_name, official_gmail, phone, address, cbu_alias, receipt_prefix)
VALUES (1, 'Club Tucumán BB', 'tucumanbbcuotas@gmail.com', '+54 381 423-1234', 'Suipacha 1160, San Miguel de Tucumán', 'TUCUMAN.BB.OFICIAL', 'TBB')
ON CONFLICT (id) DO UPDATE 
SET official_gmail = 'tucumanbbcuotas@gmail.com';

-- Actividades Oficiales
INSERT INTO activities (name, description, monthly_fee, category, schedule, color_hex) VALUES
('Básquetbol Formativo / Primera', 'Entrenamiento en cancha oficial de parqué y competencia asociativa', 18000.00, 'Básquet', 'Lun, Mié y Vie 19:30 a 21:30 hs', '#EA580C'),
('Gimnasio de Musculación & Cardio', 'Acceso libre a máquinas de fuerza, mancuernas y cintas', 15000.00, 'Gimnasio', 'Lun a Sáb 07:00 a 22:00 hs', '#0284C7'),
('Salón - Yoga & Flexibilidad', 'Clases guiadas en el salón multiuso del 1er piso', 12000.00, 'Salón', 'Mar y Jue 18:00 a 19:15 hs', '#8B5CF6'),
('Salón - Aeróbic & Funcional', 'Entrenamiento aeróbico con música y coreografías', 12000.00, 'Salón', 'Lun, Mié y Vie 18:00 a 19:00 hs', '#EC4899')
ON CONFLICT DO NOTHING;

-- Socios de Ejemplo
INSERT INTO members (full_name, dni, phone, email, category, join_date, notes) VALUES
('Lucas Martínez', '38456123', '+54 381 511-2233', 'lucas.martinez@gmail.com', 'Primera División', '15/02/2024', 'Capitán del equipo de básquet'),
('Mariana Gómez', '35987456', '+54 381 644-8899', 'mariana.gomez@gmail.com', 'Salón / Yoga', '10/03/2024', 'Socia de actividades de salón'),
('Carlos Benítez', '42111222', '+54 381 488-3322', 'carlos.benitez@gmail.com', 'Musculación', '05/01/2024', 'Entrena en el gimnasio'),
('Sofía Navarro', '40555666', '+54 381 722-1144', 'sofia.navarro@gmail.com', 'Actividades Combinadas', '18/04/2024', 'Realiza aeróbic y gimnasio')
ON CONFLICT (dni) DO NOTHING;

-- Asignación de Actividades a los Socios
-- Lucas: Básquet (id 1) + Gimnasio (id 2)
INSERT INTO member_activities (member_id, activity_id) VALUES (1, 1), (1, 2) ON CONFLICT DO NOTHING;
-- Mariana: Yoga (id 3)
INSERT INTO member_activities (member_id, activity_id) VALUES (2, 3) ON CONFLICT DO NOTHING;
-- Carlos: Gimnasio (id 2)
INSERT INTO member_activities (member_id, activity_id) VALUES (3, 2) ON CONFLICT DO NOTHING;
-- Sofía: Aeróbic (id 4) + Gimnasio (id 2)
INSERT INTO member_activities (member_id, activity_id) VALUES (4, 4), (4, 2) ON CONFLICT DO NOTHING;

-- Pagos Registrados de Ejemplo
INSERT INTO payments (member_id, activity_id, period_month, period_year, amount_paid, payment_method, receipt_number, notes) VALUES
(1, 1, 9, 2026, 18000.00, 'Transferencia', 'REC-TBB-202609-001', 'Pago de cuota Básquetbol Septiembre'),
(2, 3, 9, 2026, 12000.00, 'Efectivo', 'REC-TBB-202609-002', 'Pago mensual de Yoga')
ON CONFLICT DO NOTHING;

-- ====================================================================
-- POLÍTICAS DE SEGURIDAD (Row Level Security - RLS)
-- Permite lectura y escritura con la clave anónima (anon public key)
-- ====================================================================
ALTER TABLE club_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE members ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir lectura publica" ON club_settings FOR SELECT USING (true);
CREATE POLICY "Permitir modificacion" ON club_settings FOR ALL USING (true);

CREATE POLICY "Permitir lectura publica" ON activities FOR SELECT USING (true);
CREATE POLICY "Permitir modificacion" ON activities FOR ALL USING (true);

CREATE POLICY "Permitir lectura publica" ON members FOR SELECT USING (true);
CREATE POLICY "Permitir modificacion" ON members FOR ALL USING (true);

CREATE POLICY "Permitir lectura publica" ON member_activities FOR SELECT USING (true);
CREATE POLICY "Permitir modificacion" ON member_activities FOR ALL USING (true);

CREATE POLICY "Permitir lectura publica" ON payments FOR SELECT USING (true);
CREATE POLICY "Permitir modificacion" ON payments FOR ALL USING (true);
